
(()=>{const all=window.CASES_DATA||[];let sector="";const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));const unique=(field)=>[...new Set(all.flatMap(c=>field(c)||[]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ko"));
function fillSelect(id,vals){const el=$(id);vals.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;el.appendChild(o)})}
function sectors(){const root=$("#sector-filters");const vals=["",...unique(c=>[c.classification.sector])];vals.forEach(v=>{const n=v?all.filter(c=>c.classification.sector===v).length:all.length;const b=document.createElement("button");b.type="button";b.className="filter-chip"+(v===""?" active":"");b.dataset.sector=v;b.textContent=(v||"전체")+" ("+n+")";b.onclick=()=>{sector=v;root.querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));render()};root.appendChild(b)})}
function hay(c){return [c.id,c.title,c.classification.sector,...(c.classification.system||[]),...(c.classification.technology||[]),...(c.website.searchKeywords||[]),c.question,c.summary].filter(Boolean).join(" ").toLowerCase()}
function card(c){const systems=(c.classification.system||[]);const ev=(c.evidence.grade||[]),evNames={A:'실측·검증',B:'현장 데이터',C:'예상·잠재량',D:'Simulation'};const kws=(c.website.searchKeywords||[]).slice(0,5);return `<article class="case-card"><div class="case-card-head"><span class="case-number">${esc(c.id)}</span><span class="case-sector">${esc(c.classification.sector)}${systems[0]?" · "+esc(systems[0]):""}</span></div><h3 class="case-title">${esc(c.title)}</h3>${c.question?`<p class="case-summary">${esc(c.question)}</p>`:c.summary?`<p class="case-summary">${esc(c.summary)}</p>`:""}<div class="evidence-row">${ev.map(x=>`<span class="evidence-badge evidence-${esc(x)}">Evidence ${esc(x)} | ${esc(evNames[x]||x)}</span>`).join("")}${c.evidence.status==="EVIDENCE-PARTIAL"?'<span class="evidence-badge">PARTIAL</span>':""}</div><div class="keyword-row">${kws.map(x=>`<span class="keyword">${esc(x)}</span>`).join("")}</div><a class="case-card-link" href="${esc(c.website.url)}" aria-label="${esc(c.id+" "+c.title+" 상세 보기")}">사례 자세히 보기 →</a></article>`}
function render(){const q=$("#case-search").value.trim().toLowerCase(),sys=$("#system-filter").value,tech=$("#technology-filter").value,ev=$("#evidence-filter").value,sort=$("#sort-filter").value;let arr=all.filter(c=>(!sector||c.classification.sector===sector)&&(!q||hay(c).includes(q))&&(!sys||(c.classification.system||[]).includes(sys))&&(!tech||(c.classification.technology||[]).includes(tech))&&(!ev||(c.evidence.grade||[]).includes(ev)));if(sort==="sector")arr.sort((a,b)=>a.classification.sector.localeCompare(b.classification.sector,"ko")||a.number-b.number);else if(sort==="evidence")arr.sort((a,b)=>(a.evidence.grade||[]).join("").localeCompare((b.evidence.grade||[]).join(""))||a.number-b.number);else arr.sort((a,b)=>a.number-b.number);$("#case-grid").innerHTML=arr.map(card).join("");$("#case-result-count").textContent=arr.length;$("#case-empty").hidden=arr.length!==0}
function reset(){sector="";$("#case-search").value="";["#system-filter","#technology-filter","#evidence-filter"].forEach(x=>$(x).value="");$("#sort-filter").value="number";document.querySelectorAll(".filter-chip").forEach((x,i)=>x.classList.toggle("active",i===0));render()}
sectors();fillSelect("#system-filter",unique(c=>c.classification.system));fillSelect("#technology-filter",unique(c=>c.classification.technology));fillSelect("#evidence-filter",unique(c=>c.evidence.grade));["#case-search","#system-filter","#technology-filter","#evidence-filter","#sort-filter"].forEach(x=>$(x).addEventListener(x==="#case-search"?"input":"change",render));$("#case-reset").onclick=reset;document.querySelector("[data-reset-cases]").onclick=reset;render()})();
